spring:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      encoding: utf8

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 

  jpa:
    # defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true

  
